"""rename email_address to email

Revision ID: 3a2d96d7a869
Revises: 2eb0875e1dba
Create Date: 2026-06-21 21:16:46.133086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2d96d7a869'
down_revision: Union[str, Sequence[str], None] = '2eb0875e1dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user_account', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_user_account_email_address'), table_name='user_account')
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.drop_column('user_account', 'email_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('email_address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.create_index(op.f('ix_user_account_email_address'), 'user_account', ['email_address'], unique=True)
    op.drop_column('user_account', 'is_active')
    op.drop_column('user_account', 'email')
    # ### end Alembic commands ###
